const SET_SEARCH_QUERY = 'search/SET_SEARCH_QUERY';
const SET_SEARCH_RESULTS = 'search/SET_SEARCH_RESULTS';
const CLEAR_SEARCH_RESULTS = 'search/CLEAR_SEARCH_RESULTS';

export const types = {
  SET_SEARCH_QUERY,
  SET_SEARCH_RESULTS,
  CLEAR_SEARCH_RESULTS,
};
